#!/bin/sh

case `uname -s` in
    CYGWIN*)
	TargetDir=`pwd | sed -e 's_/cygdrive/\([^/]\+\)_\1\:_'`
	(cd "`dirname $0`"; ./newmoon-mz $NEWMOON_FLAGS $TargetDir/$1) && \
	(cd "`dirname $0`"/backend/dotnet; make $TargetDir/`basename $1 .scm`.dll)
	;;
    *)
	TargetDir=`pwd`
	(cd "`dirname $0`"; ./newmoon-mz $NEWMOON_FLAGS $TargetDir/$1) && \
	(cd "`dirname $0`"/backend/dotnet; make $TargetDir/`basename $1 .scm`.dll)
	;;
esac
